springfox:
  documentation:
    swagger-ui:
      enabled: true
  springfox-swagger2:
    enabled: true

swagger:
  title: Titre de votre API
  description: Description de votre API
  version: 1.0
  base-package: com.example
